# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("http://localhost:3000/map")
    self.driver.set_window_size(1850, 1053)
    self.driver.implicitly_wait(10)
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-circle-link:nth-child(1) > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-circle-link:nth-child(1) > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div > div > .cognito-asf #signInFormUsername").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div > div > .cognito-asf #signInFormUsername").send_keys("kokid46398@rdluxe.com")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div > div > .cognito-asf #signInFormPassword").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div > div > .cognito-asf #signInFormPassword").send_keys("Sus@naAgui4r")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div > div > .cognito-asf > .btn").click()
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.ID, "ori-dst-btn").click()
    self.driver.find_element(By.ID, "add-intermediate-btn").click()
    self.driver.find_element(By.ID, "origin-input").click()
    self.driver.find_element(By.ID, "origin-input").send_keys("Viseu")
    self.driver.find_element(By.ID, "intermediate-input-0").click()
    self.driver.find_element(By.ID, "intermediate-input-0").send_keys("Sátão")
    self.driver.find_element(By.ID, "destination-input").click()
    self.driver.find_element(By.ID, "destination-input").send_keys("Mangualde")
    self.driver.find_element(By.ID, "get-route-btn").click()
  
if __name__ == '__main__':
    pytest.main()